apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-{{ .Values.app.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}
      version: {{ .Values.app.version }}
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}
        version: {{ .Values.app.version }}
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: APP_VERSION
              value: "{{ .Values.app.version }}"