apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-{{ .Values.app.version }}
spec:
  selector:
    app: {{ include "myapp.name" . }}
    version: {{ .Values.app.version }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80