apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sandhya19/eks-bluegreen-argocd'
    targetRevision: HEAD
    path: charts/myapp
    helm:
      parameters:
        - name: app.version
          value: green
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true