replicaCount: 2
image:
  repository: your-dockerhub-username/flask-bluegreen
  tag: v1
  pullPolicy: IfNotPresent

app:
  version: blue

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false